# Generated by Django 6.0.7 on 2026-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
