# Generated by Django 6.0.7 on 2026-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.CharField(default='Patna', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='state',
            field=models.CharField(default='Bihar', max_length=100),
        ),
    ]
