# Generated by Django 6.0.7 on 2026-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_district_alter_center_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='district',
            field=models.CharField(choices=[('PTN', 'Patna'), ('GYA', 'Gaya'), ('MUZ', 'Muzaffarpur'), ('BGP', 'Bhagalpur')], max_length=10),
        ),
    ]
